In [4]:
# Write a function to compute 5/0 and use try/except to catch the exceptions.

def compute(num1,num2):
    try:
        print(num1/num2)
    except ZeroDivisionError:
        print("can't divide by zero")

compute(5,0)        

can't divide by zero


In [10]:
# Implement a Python program to generate all sentences where subject is in ["Americans",
# "Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

for sub in subjects:
    for verb in verbs:
        for obj in objects:
            print(sub,verb,obj)

Americans  play Baseball
Americans  play Cricket
Americans  watch Baseball
Americans  watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


In [102]:
# Write a function so that the columns of the output matrix are powers of the input vector.
# The order of the powers is determined by the increasing boolean argument. Specifically, when
# increasing is False, the i-th output column is the input vector raised element-wise to the power
# of N - i - 1.

def vander_matrix(x,n,increasing = False):
    if not increasing:
        try:
            output = np.array([j**(n-1-i) for j in x for i in range(n)]).reshape(len(x),n)
        except:
            output = np.array([j**(len(x)-1-i) for j in x for i in range(len(x))]).reshape(len(x),len(x))
    else:
        try:
            output = np.array([j**(i) for j in x for i in range(n)]).reshape(len(x),n)
        except:
            output = np.array([j**(i) for j in x for i in range(len(x))]).reshape(len(x),len(x))
           
    return output


In [106]:
y = np.array([1,2,3,5])
vander_matrix(y)

array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 27,   9,   3,   1],
       [125,  25,   5,   1]])

In [107]:
y = np.array([2,3,4,5])
vander_matrix(y,increasing = True)

array([[  1,   2,   4,   8],
       [  1,   3,   9,  27],
       [  1,   4,  16,  64],
       [  1,   5,  25, 125]])

In [108]:
y = np.array([2,3,4,5])
vander_matrix(y,3)

array([[ 4,  2,  1],
       [ 9,  3,  1],
       [16,  4,  1],
       [25,  5,  1]])

In [114]:
y = np.array([2,3,4,5])
vander_matrix(y,3,True)

array([[ 1,  2,  4],
       [ 1,  3,  9],
       [ 1,  4, 16],
       [ 1,  5, 25]])